'use client';
import {useMemo,useState} from 'react';
type RefImage={name:string,url:string};
type Template={name:string,icon:string,desc:string,mode:string,style:string,brief:string};
const styles=['Hollywood Epic','Afro-Cinematic','Gospel Radiance','Neo-Noir','Desert Prophetic','Arena Performance'];
const modes=['Auto Director','Performance','Narrative','Lyrics Visualizer','Hybrid'];
const templates:Template[]=[
{name:'Epic Performance',icon:'🎤',desc:'Arena-scale performance, moving lights, crowd energy and heroic camera moves.',mode:'Performance',style:'Arena Performance',brief:'A high-energy live performance with sweeping crane shots, intimate singing close-ups, crowd response, dramatic backlights and beat-driven edits.'},
{name:'Gospel Worship',icon:'✨',desc:'Spirit-filled worship, congregation, warm light and intimate performance coverage.',mode:'Hybrid',style:'Gospel Radiance',brief:'A reverent cinematic worship journey combining intimate vocal performance, congregation response, radiant light, prayerful moments and uplifting visual crescendos.'},
{name:'Storyteller',icon:'🎬',desc:'Turn lyrics into a narrative film with performance inserts and recurring visual motifs.',mode:'Narrative',style:'Hollywood Epic',brief:'A lyric-driven cinematic story with a clear emotional arc, recurring symbols, establishing shots, dramatic character moments and carefully placed artist performance inserts.'},
{name:'Faith & Victory',icon:'✝',desc:'Triumph, testimony, mountains, breakthrough and victorious performance imagery.',mode:'Hybrid',style:'Hollywood Epic',brief:'A journey from adversity into victory using mountains, dawn, open skies, testimony imagery and powerful artist performance, building toward a triumphant final chorus.'},
{name:'Royal Dominion',icon:'♛',desc:'Prestige, throne-room scale, gold, authority and elegant cinematic movement.',mode:'Performance',style:'Hollywood Epic',brief:'A regal performance world with monumental architecture, restrained gold accents, throne-room scale, elegant dolly movement, strong silhouettes and commanding close-ups.'},
{name:'Prophetic Fire',icon:'🔥',desc:'Prayer, scripture, firelight, atmosphere and spiritually charged visual storytelling.',mode:'Hybrid',style:'Desert Prophetic',brief:'A spiritually charged cinematic journey using scripture, firelight, watchman imagery, prayer, atmospheric landscapes and intense performance close-ups without visual clutter.'},
{name:'Afro-Cinematic',icon:'🌍',desc:'Contemporary African visual identity, culture, movement, landscape and premium fashion.',mode:'Hybrid',style:'Afro-Cinematic',brief:'A premium contemporary African music film blending elegant fashion, architecture, landscape, community, movement and artist performance with international cinematic polish.'},
{name:'City After Dark',icon:'🌃',desc:'Neon streets, rooftops, cars, reflections and modern nocturnal performance.',mode:'Performance',style:'Neo-Noir',brief:'A stylish night-city performance across rooftops, wet streets, neon interiors and moving vehicles, using reflections, shallow depth and rhythmic handheld-to-dolly camera changes.'},
{name:'Nature Escape',icon:'🏔',desc:'Mountains, oceans, sunrise and expansive visual breathing room.',mode:'Narrative',style:'Hollywood Epic',brief:'An expansive visual journey through mountains, ocean, sunrise and open landscapes, balancing contemplative artist portraits with sweeping cinematic environments.'},
{name:'Studio Session',icon:'🎙',desc:'Clean premium studio performance optimized for facial detail and precise lip sync.',mode:'Performance',style:'Gospel Radiance',brief:'A premium controlled studio performance prioritizing facial detail, clean lighting, microphone coverage, natural gestures, precise lip sync and elegant camera movement.'},
{name:'Lyrics Visualizer',icon:'✍',desc:'Typography, lyric cues, abstract motion and selective artist appearances.',mode:'Lyrics Visualizer',style:'Hollywood Epic',brief:'A sophisticated lyric-led visualizer with kinetic typography, semantic imagery, abstract cinematic textures and selective artist appearances synchronized to important lines.'},
{name:'One-Take Intimate',icon:'🎥',desc:'Emotion-first close performance with subtle camera movement and minimal cuts.',mode:'Performance',style:'Gospel Radiance',brief:'An intimate performance built around long takes, expressive close-ups, subtle push-ins, authentic gestures and near-continuous facial visibility for maximum emotional connection.'}
];
const shots=['Aerial establishing shot','35mm hero close-up','Handheld performance shot','Slow dolly push-in','Crane reveal','Backlit silhouette','Wide crowd energy','Intimate profile close-up'];
export default function Home(){
 const [audio,setAudio]=useState<File|null>(null),[images,setImages]=useState<RefImage[]>([]),[style,setStyle]=useState(styles[0]),[mode,setMode]=useState(modes[0]),[ratio,setRatio]=useState('16:9'),[story,setStory]=useState('A triumphant cinematic journey from darkness into light, driven by the emotion and rhythm of the song.'),[generated,setGenerated]=useState(false),[selectedTemplate,setSelectedTemplate]=useState('Custom');
 const [identity,setIdentity]=useState(true),[beatSync,setBeatSync]=useState(true),[lyrics,setLyrics]=useState(true),[grade,setGrade]=useState(true),[lipSync,setLipSync]=useState(true),[phonemes,setPhonemes]=useState(true),[faceTrack,setFaceTrack]=useState(true),[syncQc,setSyncQc]=useState(true);
 const audioUrl=useMemo(()=>audio?URL.createObjectURL(audio):'', [audio]);
 function addImages(files:FileList|null){if(!files)return;setImages(p=>[...p,...Array.from(files).map(f=>({name:f.name,url:URL.createObjectURL(f)}))].slice(0,12))}
 function applyTemplate(t:Template){setSelectedTemplate(t.name);setMode(t.mode);setStyle(t.style);setStory(t.brief);if(t.name==='Studio Session'||t.name==='One-Take Intimate'){setLipSync(true);setPhonemes(true);setFaceTrack(true);setSyncQc(true)}}
 const Toggle=({label,value,set}:{label:string,value:boolean,set:(v:boolean)=>void})=><button className={value?'on':''} onClick={()=>set(!value)}>{value?'✓ ':''}{label}</button>;
 return <main><nav><b>MABRIG <span>VERSE</span></b><div className="pill">AI MUSIC VIDEO WORKSTATION</div></nav>
 <section className="hero"><p className="eyebrow">FROM SOUND TO CINEMA</p><h1>Turn your song into a <em>cinematic world.</em></h1><p>Choose a production template or direct from scratch. Every template remains fully editable.</p></section>
 <section className="output"><p className="eyebrow">MUSIC VIDEO TEMPLATE LIBRARY</p><h2>Start with a director-built visual language.</h2><p>Templates configure the production mode, visual language and creative brief. Your uploaded reference images become the artist/character identity source.</p><div className="templateGrid">{templates.map(t=><button key={t.name} className={selectedTemplate===t.name?'templateCard on':'templateCard'} onClick={()=>applyTemplate(t)}><b>{t.icon} {t.name}</b><span>{t.desc}</span><small>{t.mode} · {t.style}</small></button>)}</div></section>
 <section className="studio"><div className="panel"><h2>01 · Media Library</h2><label className="drop"><input type="file" accept="audio/mpeg,audio/wav,.mp3,.wav" onChange={e=>setAudio(e.target.files?.[0]||null)}/><strong>{audio?audio.name:'Drop your master audio'}</strong><small>MP3 / WAV · waveform + vocal + phoneme analysis</small></label>{audioUrl&&<audio controls src={audioUrl}/>}<label className="drop images"><input type="file" accept="image/*" multiple onChange={e=>addImages(e.target.files)}/><strong>+ Artist & world references</strong><small>Your face/artist references drive Identity Lock · up to 12</small></label><div className="refs">{images.map((x,i)=><img key={i} src={x.url} alt={x.name}/>)}</div></div>
 <div className="panel"><h2>02 · AI Director</h2><label>Selected template</label><div className="pill">{selectedTemplate}</div><label>Production mode</label><div className="chips">{modes.map(x=><button className={mode===x?'on':''} onClick={()=>{setMode(x);setSelectedTemplate('Custom')}} key={x}>{x}</button>)}</div><label>Visual language</label><div className="chips">{styles.map(x=><button className={style===x?'on':''} onClick={()=>{setStyle(x);setSelectedTemplate('Custom')}} key={x}>{x}</button>)}</div><label>Creative brief</label><textarea value={story} onChange={e=>setStory(e.target.value)}/><label>Music intelligence</label><div className="chips"><Toggle label="Beat Sync" value={beatSync} set={setBeatSync}/><Toggle label="Lyrics Map" value={lyrics} set={setLyrics}/><Toggle label="Identity Lock" value={identity} set={setIdentity}/><Toggle label="Cinematic Grade" value={grade} set={setGrade}/></div><label>Precision Lip Sync</label><div className="chips"><Toggle label="Vocal Lip Sync" value={lipSync} set={setLipSync}/><Toggle label="Phoneme Alignment" value={phonemes} set={setPhonemes}/><Toggle label="Face Tracking" value={faceTrack} set={setFaceTrack}/><Toggle label="Sync QC" value={syncQc} set={setSyncQc}/></div><label>Master format</label><div className="chips">{['16:9','9:16','1:1','4:5','2.39:1'].map(x=><button className={ratio===x?'on':''} onClick={()=>setRatio(x)} key={x}>{x}</button>)}</div><button className="generate" disabled={!audio} onClick={()=>setGenerated(true)}>✦ Build Director Timeline</button></div></section>
 {generated&&<section className="output"><p className="eyebrow">{selectedTemplate.toUpperCase()} · AI DIRECTOR</p><h2>{style} · {ratio}</h2><p>{story}</p><div className="timeline">{shots.map((s,i)=><article key={s}><b>{String(i+1).padStart(2,'0')}</b><div><strong>{s}</strong><p>{i%2?'Performance · vocal timestamp · phoneme window · face landmarks · identity locked.':'Narrative/B-roll · lyric cue · continuity checked · beat-aware transition.'}</p></div><span>{i*15}s</span></article>)}</div><div className="render"><b>Template-aware production pipeline</b><span>Template → song analysis → references → storyboard → lip sync → generation → QC → edit → grade → master</span></div></section>}
 <footer>MABRIG VERSE · AI-NATIVE MUSIC VIDEO WORKSTATION</footer></main>
}